Test.assert_equals(multiply(1,1), 1)
Test.assert_equals(multiply(2,1), 2)
Test.assert_equals(multiply(2,2), 4)
Test.assert_equals(multiply(3,5), 15)
Test.assert_equals(multiply(1.5,2.5), 3.75)
Test.assert_equals(multiply(0,5), 0)
Test.assert_equals(multiply(0,0), 0)